version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
