apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-container
        image: raemondarellano/act10app:latest
        ports:
        - containerPort: 3000
        env:
         - name: MONGO_URI
           value: mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@$(MONGO_HOST):27017/$(MONGO_DATABASE)?authSource=admin

         - name: MONGO_USER         #mongo username
           valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username

         - name: MONGO_PASSWORD     #mongo password
           valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password

         - name: MONGO_HOST        #mongo host
           valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url

         - name: MONGO_DATABASE     # mongo database name
           valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_name

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
#      nodePort: 30000

